export const one = [1]
export const two = [1,2]
export const three = [1,2,3]
export const numbers = [one,two,three]
export const colors = ["red", "darkblue", "black"]
export const shapes = ["square", "circle", "oval"]
export const fills = ["solid", "empty", "fill"]